services:
  webapp:
    build: ./webapp
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build: ./server
    restart: always
    ports:
      - 5000:5000